import { Professor } from "../interfaces/Professors";

export const professorsData: Professor[] = [
  {
    id: "1",
    name: "Dr. João Silva",
    email: "joao.silva@fatecvotorantim.edu.br",
    titration: "Doutor",
    registrationNumber: "123456",
    unitId: "301 - Votorantim",
    lattes: "http://lattes.cnpq.br/123456789",
    reference: "PES I - A",
    notes: "Professor com experiência em TI.",
    activityStatus: "Ativo",
    courses: ["DSM", "CO"],
  },
  {
    id: "2",
    name: "Profa. Maria Souza",
    email: "maria.souza@fatecvotorantim.edu.br",
    titration: "Mestre",
    registrationNumber: "654321",
    unitId: "123 - Sorocaba",
    lattes: "http://lattes.cnpq.br/987654321",
    reference: "PES II - B",
    notes: "Professora com foco em redes.",
    activityStatus: "Inativo",
    courses: ["CO", "CDN"],
  },
  {
    id: "3",
    name: "Dr. João Silva",
    email: "joao.silva@fatecvotorantim.edu.br",
    titration: "Doutor",
    registrationNumber: "123456",
    unitId: "301 - Votorantim",
    lattes: "http://lattes.cnpq.br/123456789",
    reference: "PES I - A",
    notes: "Professor com experiência em TI.",
    activityStatus: "Ativo",
    courses: ["DSM", "CO"],
  },
  {
    id: "4",
    name: "Profa. Maria Souza",
    email: "maria.souza@fatecvotorantim.edu.br",
    titration: "Mestre",
    registrationNumber: "654321",
    unitId: "123 - Sorocaba",
    lattes: "http://lattes.cnpq.br/987654321",
    reference: "PES II - B",
    notes: "Professora com foco em redes.",
    activityStatus: "Inativo",
    courses: ["CO", "CDN"],
  },
  {
    id: "5",
    name: "Dr. João Silva",
    email: "joao.silva@fatecvotorantim.edu.br",
    titration: "Doutor",
    registrationNumber: "123456",
    unitId: "301 - Votorantim",
    lattes: "http://lattes.cnpq.br/123456789",
    reference: "PES I - A",
    notes: "Professor com experiência em TI.",
    activityStatus: "Ativo",
    courses: ["DSM", "CO"],
  },
  {
    id: "6",
    name: "Profa. Maria Souza",
    email: "maria.souza@fatecvotorantim.edu.br",
    titration: "Mestre",
    registrationNumber: "654321",
    unitId: "123 - Sorocaba",
    lattes: "http://lattes.cnpq.br/987654321",
    reference: "PES II - B",
    notes: "Professora com foco em redes.",
    activityStatus: "Inativo",
    courses: ["CO", "CDN"],
  },
];
